apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: wmug
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wmug
    app.kubernetes.io/part-of: byoc-app-rqky
  name: wmug
spec:
  rules:
  - host: wmug-byoc-bgzm-tenant.apps.37881849f70562923b04.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: wmug
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
