apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: wmug
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wmug
    app.kubernetes.io/part-of: byoc-app-rqky
  name: wmug
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: wmug
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: wmug
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-bgzm-tenant/byoc-app-rqky/wmug@sha256:04a066050de634b6e5ac15a1c7993707d9a9e7b8c2a9afe92c5772adb3942d79
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
