apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: wmug
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wmug
    app.kubernetes.io/part-of: byoc-app-rqky
  name: wmug
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: wmug
status:
  loadBalancer: {}
